name: jhentai
description: A flutter app for E-Hentai/EXHentai

publish_to: 'none'
version: 7.4.11+151

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # rewrite file mode
  dio:
    git:
      url: https://github.com/jiangtian616/dio
      path: dio
      ref: append-mode
  get: 4.6.5
  get_storage: 2.0.3
  extended_nested_scroll_view: 6.1.1
  flukit: 3.0.1
  html: 0.15.1
  logger: 1.1.0
  flutter_rating_bar: 4.0.1
  waterfall_flow: 3.0.2
  extended_image: 8.1.0
  font_awesome_flutter: 9.2.0
  intl: 0.18.1
  collection: 1.18.0
  clipboard: 0.1.3
  scrollable_positioned_list: 0.3.5
  flutter_list_view: 1.1.21
  executor: 2.2.2
  retry: 3.1.2
  path: 1.8.3
  drift: 2.14.1
  sqlite3_flutter_libs: 0.5.20
  path_provider: 2.0.15
  flutter_slidable: 3.0.0
  flutter_widget_from_html: 0.14.10+1
  url_launcher: 6.1.8
  like_button: 2.0.5
  webview_flutter: 4.2.2
  # rewrite double tap & tap drag gesture
  photo_view:
    git:
      url: https://github.com/jiangtian616/photo_view/
      ref: separate
  package_info_plus: 4.0.2
  file_picker: 5.3.0
  local_auth: 2.1.6
  blur: 3.1.0
  flutter_windowmanager: 0.2.0
  animate_do: 2.1.0
  share_plus: 4.5.3
  syncfusion_flutter_charts: 22.2.11
  archive: 3.4.10
  fluttertoast: 8.1.2
  battery_plus: 3.0.2
  throttling: 1.0.0
  receive_sharing_intent: 1.4.5
  window_manager:
    # https://github.com/leanflutter/window_manager/pull/409
    git:
      url: https://github.com/damywise/window_manager
      branch: fullscreen-events
  permission_handler: 9.2.0
  grouped_list: 5.1.2
  resizable_widget:
    git: https://github.com/eurisit/resizable_widget
  loading_animation_widget: 1.2.0+4
  simple_animations: 5.0.2
  animated_flip_counter: 0.2.6
  image_save: 5.0.0
  system_network_proxy: 1.0.2
  http_proxy: 1.2.1
  flutter_socks_proxy: 0.0.3
  flutter_draggable_gridview:
    # remove assert
    git: https://github.com/jiangtian616/flutter_draggable_gridview
  flutter_displaymode: 0.5.0
  pinput: 2.2.31
  wakelock_plus: 1.1.1
  material_color_utilities: 0.5.0
  flex_color_picker: 3.1.0
  zoom_widget: 2.0.1
  android_intent_plus: 3.1.7
  integral_isolates: 0.4.1
  screen_brightness: 0.2.2+1
  crypto: 3.0.3
  csv: 5.1.1

dependency_overrides:
  test_api: 0.6.0
  matcher: 0.12.16
  chewie: 1.7.0
  http: 1.1.0
  cached_network_image: 3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: 1.24.3
  drift_dev: 2.14.1
  build_runner: ^2.1.8
  flutter_launcher_icons: 0.11.0



flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#fce219"
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"
  windows:
    generate: true
    image_path: "assets/icon-ios.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon-ios.png"
